package stoni_bean;
// Generated 24/08/2017 11:33:26 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Equipamento generated by hbm2java
 */
public class Equipamento  implements java.io.Serializable {


     private Integer idEquipamento;
     private String nomeEquipamento;
     private String marcaEquipamento;
     private String jobNameEquipamento;
     private String jobNumberEquipamento;
     private String jobUsernameEquipmaneto;
     private String jobTypeEquipamento;
     private String jobPagecountEquipamento;
     private Integer jobListCountEquipamento;
     private Integer liveStatusEquipamento;
     private String jobDateEquipamento;
     private Set tems = new HashSet(0);

    public Equipamento() {
    }

    public Equipamento(String nomeEquipamento, String marcaEquipamento, String jobNameEquipamento, String jobNumberEquipamento, String jobUsernameEquipmaneto, String jobTypeEquipamento, String jobPagecountEquipamento, Integer jobListCountEquipamento, Integer liveStatusEquipamento, String jobDateEquipamento, Set tems) {
       this.nomeEquipamento = nomeEquipamento;
       this.marcaEquipamento = marcaEquipamento;
       this.jobNameEquipamento = jobNameEquipamento;
       this.jobNumberEquipamento = jobNumberEquipamento;
       this.jobUsernameEquipmaneto = jobUsernameEquipmaneto;
       this.jobTypeEquipamento = jobTypeEquipamento;
       this.jobPagecountEquipamento = jobPagecountEquipamento;
       this.jobListCountEquipamento = jobListCountEquipamento;
       this.liveStatusEquipamento = liveStatusEquipamento;
       this.jobDateEquipamento = jobDateEquipamento;
       this.tems = tems;
    }
   
    public Integer getIdEquipamento() {
        return this.idEquipamento;
    }
    
    public void setIdEquipamento(Integer idEquipamento) {
        this.idEquipamento = idEquipamento;
    }
    public String getNomeEquipamento() {
        return this.nomeEquipamento;
    }
    
    public void setNomeEquipamento(String nomeEquipamento) {
        this.nomeEquipamento = nomeEquipamento;
    }
    public String getMarcaEquipamento() {
        return this.marcaEquipamento;
    }
    
    public void setMarcaEquipamento(String marcaEquipamento) {
        this.marcaEquipamento = marcaEquipamento;
    }
    public String getJobNameEquipamento() {
        return this.jobNameEquipamento;
    }
    
    public void setJobNameEquipamento(String jobNameEquipamento) {
        this.jobNameEquipamento = jobNameEquipamento;
    }
    public String getJobNumberEquipamento() {
        return this.jobNumberEquipamento;
    }
    
    public void setJobNumberEquipamento(String jobNumberEquipamento) {
        this.jobNumberEquipamento = jobNumberEquipamento;
    }
    public String getJobUsernameEquipmaneto() {
        return this.jobUsernameEquipmaneto;
    }
    
    public void setJobUsernameEquipmaneto(String jobUsernameEquipmaneto) {
        this.jobUsernameEquipmaneto = jobUsernameEquipmaneto;
    }
    public String getJobTypeEquipamento() {
        return this.jobTypeEquipamento;
    }
    
    public void setJobTypeEquipamento(String jobTypeEquipamento) {
        this.jobTypeEquipamento = jobTypeEquipamento;
    }
    public String getJobPagecountEquipamento() {
        return this.jobPagecountEquipamento;
    }
    
    public void setJobPagecountEquipamento(String jobPagecountEquipamento) {
        this.jobPagecountEquipamento = jobPagecountEquipamento;
    }
    public Integer getJobListCountEquipamento() {
        return this.jobListCountEquipamento;
    }
    
    public void setJobListCountEquipamento(Integer jobListCountEquipamento) {
        this.jobListCountEquipamento = jobListCountEquipamento;
    }
    public Integer getLiveStatusEquipamento() {
        return this.liveStatusEquipamento;
    }
    
    public void setLiveStatusEquipamento(Integer liveStatusEquipamento) {
        this.liveStatusEquipamento = liveStatusEquipamento;
    }
    public String getJobDateEquipamento() {
        return this.jobDateEquipamento;
    }
    
    public void setJobDateEquipamento(String jobDateEquipamento) {
        this.jobDateEquipamento = jobDateEquipamento;
    }
    public Set getTems() {
        return this.tems;
    }
    
    public void setTems(Set tems) {
        this.tems = tems;
    }




}


