package stoni_bean;
// Generated 24/08/2017 11:33:26 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Identidade generated by hbm2java
 */
public class Identidade  implements java.io.Serializable {


     private Integer idIdentidade;
     private String nomeIdentidade;
     private String loginIdentidade;
     private Integer passwordIdentidade;
     private Integer pincodeIdentidade;
     private Integer possuiIdIdentidade;
     private Set impressaos = new HashSet(0);
     private Set tems = new HashSet(0);

    public Identidade() {
    }

    public Identidade(String nomeIdentidade, String loginIdentidade, Integer passwordIdentidade, Integer pincodeIdentidade, Integer possuiIdIdentidade, Set impressaos, Set tems) {
       this.nomeIdentidade = nomeIdentidade;
       this.loginIdentidade = loginIdentidade;
       this.passwordIdentidade = passwordIdentidade;
       this.pincodeIdentidade = pincodeIdentidade;
       this.possuiIdIdentidade = possuiIdIdentidade;
       this.impressaos = impressaos;
       this.tems = tems;
    }
   
    public Integer getIdIdentidade() {
        return this.idIdentidade;
    }
    
    public void setIdIdentidade(Integer idIdentidade) {
        this.idIdentidade = idIdentidade;
    }
    public String getNomeIdentidade() {
        return this.nomeIdentidade;
    }
    
    public void setNomeIdentidade(String nomeIdentidade) {
        this.nomeIdentidade = nomeIdentidade;
    }
    public String getLoginIdentidade() {
        return this.loginIdentidade;
    }
    
    public void setLoginIdentidade(String loginIdentidade) {
        this.loginIdentidade = loginIdentidade;
    }
    public Integer getPasswordIdentidade() {
        return this.passwordIdentidade;
    }
    
    public void setPasswordIdentidade(Integer passwordIdentidade) {
        this.passwordIdentidade = passwordIdentidade;
    }
    public Integer getPincodeIdentidade() {
        return this.pincodeIdentidade;
    }
    
    public void setPincodeIdentidade(Integer pincodeIdentidade) {
        this.pincodeIdentidade = pincodeIdentidade;
    }
    public Integer getPossuiIdIdentidade() {
        return this.possuiIdIdentidade;
    }
    
    public void setPossuiIdIdentidade(Integer possuiIdIdentidade) {
        this.possuiIdIdentidade = possuiIdIdentidade;
    }
    public Set getImpressaos() {
        return this.impressaos;
    }
    
    public void setImpressaos(Set impressaos) {
        this.impressaos = impressaos;
    }
    public Set getTems() {
        return this.tems;
    }
    
    public void setTems(Set tems) {
        this.tems = tems;
    }




}


