package stoni_bean;
// Generated 24/08/2017 11:33:26 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Impressora generated by hbm2java
 */
public class Impressora  implements java.io.Serializable {


     private Integer idImpressora;
     private String ipImpressora;
     private String nomeImpressora;
     private String descricaoImpressora;
     private Set impressaos = new HashSet(0);
     private Set tems = new HashSet(0);

    public Impressora() {
    }

    public Impressora(String ipImpressora, String nomeImpressora, String descricaoImpressora, Set impressaos, Set tems) {
       this.ipImpressora = ipImpressora;
       this.nomeImpressora = nomeImpressora;
       this.descricaoImpressora = descricaoImpressora;
       this.impressaos = impressaos;
       this.tems = tems;
    }
   
    public Integer getIdImpressora() {
        return this.idImpressora;
    }
    
    public void setIdImpressora(Integer idImpressora) {
        this.idImpressora = idImpressora;
    }
    public String getIpImpressora() {
        return this.ipImpressora;
    }
    
    public void setIpImpressora(String ipImpressora) {
        this.ipImpressora = ipImpressora;
    }
    public String getNomeImpressora() {
        return this.nomeImpressora;
    }
    
    public void setNomeImpressora(String nomeImpressora) {
        this.nomeImpressora = nomeImpressora;
    }
    public String getDescricaoImpressora() {
        return this.descricaoImpressora;
    }
    
    public void setDescricaoImpressora(String descricaoImpressora) {
        this.descricaoImpressora = descricaoImpressora;
    }
    public Set getImpressaos() {
        return this.impressaos;
    }
    
    public void setImpressaos(Set impressaos) {
        this.impressaos = impressaos;
    }
    public Set getTems() {
        return this.tems;
    }
    
    public void setTems(Set tems) {
        this.tems = tems;
    }




}


