package stoni_bean;
// Generated 24/08/2017 11:33:26 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Impressao generated by hbm2java
 */
public class Impressao  implements java.io.Serializable {

     private String nomeIdentidade;
     private Long idImpressao;
     private Identidade identidade;
     private Impressora impressora;
     private String tipoImprime;
     private Integer qtdPaginasImprime;
     private Double valorImprime;
     private Double statusImprime;
     private String nomeDoArquivoImprime;
     private Date dataImprime;

    public Impressao() {
    }

    public Impressao(Identidade identidade, Impressora impressora, String tipoImprime, Integer qtdPaginasImprime, Double valorImprime, Double statusImprime, String nomeDoArquivoImprime, Date dataImprime) {
       this.identidade = identidade;
       this.impressora = impressora;
       this.tipoImprime = tipoImprime;
       this.qtdPaginasImprime = qtdPaginasImprime;
       this.valorImprime = valorImprime;
       this.statusImprime = statusImprime;
       this.nomeDoArquivoImprime = nomeDoArquivoImprime;
       this.dataImprime = dataImprime;
    }

    public String getNomeIdentidade() {
        return nomeIdentidade;
    }

    public void setNomeIdentidade(String nomeIdentidade) {
        this.nomeIdentidade = nomeIdentidade;
    }
   
    public Long getIdImpressao() {
        return this.idImpressao;
    }
    
    public void setIdImpressao(Long idImpressao) {
        this.idImpressao = idImpressao;
    }
    public Identidade getIdentidade() {
        return this.identidade;
    }
    
    public void setIdentidade(Identidade identidade) {
        this.identidade = identidade;
    }
    public Impressora getImpressora() {
        return this.impressora;
    }
    
    public void setImpressora(Impressora impressora) {
        this.impressora = impressora;
    }
    public String getTipoImprime() {
        return this.tipoImprime;
    }
    
    public void setTipoImprime(String tipoImprime) {
        this.tipoImprime = tipoImprime;
    }
    public Integer getQtdPaginasImprime() {
        return this.qtdPaginasImprime;
    }
    
    public void setQtdPaginasImprime(Integer qtdPaginasImprime) {
        this.qtdPaginasImprime = qtdPaginasImprime;
    }
    public Double getValorImprime() {
        return this.valorImprime;
    }
    
    public void setValorImprime(Double valorImprime) {
        this.valorImprime = valorImprime;
    }
    public Double getStatusImprime() {
        return this.statusImprime;
    }
    
    public void setStatusImprime(Double statusImprime) {
        this.statusImprime = statusImprime;
    }
    public String getNomeDoArquivoImprime() {
        return this.nomeDoArquivoImprime;
    }
    
    public void setNomeDoArquivoImprime(String nomeDoArquivoImprime) {
        this.nomeDoArquivoImprime = nomeDoArquivoImprime;
    }
    public Date getDataImprime() {
        return this.dataImprime;
    }
    
    public void setDataImprime(Date dataImprime) {
        this.dataImprime = dataImprime;
    }

    @Override
    public String toString() {
        return "Impressao{" + "nomeIdentidade=" + nomeIdentidade + ", tipoImprime=" + tipoImprime + ", qtdPaginasImprime=" + qtdPaginasImprime + ", valorImprime=" + valorImprime + ", statusImprime=" + statusImprime + ", nomeDoArquivoImprime=" + nomeDoArquivoImprime + ", dataImprime=" + dataImprime + '}';
    }




}


