package stoni_bean;
// Generated 24/08/2017 11:33:26 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Preco generated by hbm2java
 */
public class Preco  implements java.io.Serializable {


     private Integer idPerfil;
     private String nomePerfil;
     private Double a4ColorPerfil;
     private Double a4PbPerfil;
     private Double a3ColorPerfil;
     private Double a3PbPerfil;
     private Double outrosPbPerfil;
     private Double outrosColorPerfil;
     private Set tems = new HashSet(0);

    public Preco() {
    }

    public Preco(String nomePerfil, Double a4ColorPerfil, Double a4PbPerfil, Double a3ColorPerfil, Double a3PbPerfil, Double outrosPbPerfil, Double outrosColorPerfil, Set tems) {
       this.nomePerfil = nomePerfil;
       this.a4ColorPerfil = a4ColorPerfil;
       this.a4PbPerfil = a4PbPerfil;
       this.a3ColorPerfil = a3ColorPerfil;
       this.a3PbPerfil = a3PbPerfil;
       this.outrosPbPerfil = outrosPbPerfil;
       this.outrosColorPerfil = outrosColorPerfil;
       this.tems = tems;
    }
   
    public Integer getIdPerfil() {
        return this.idPerfil;
    }
    
    public void setIdPerfil(Integer idPerfil) {
        this.idPerfil = idPerfil;
    }
    public String getNomePerfil() {
        return this.nomePerfil;
    }
    
    public void setNomePerfil(String nomePerfil) {
        this.nomePerfil = nomePerfil;
    }
    public Double getA4ColorPerfil() {
        return this.a4ColorPerfil;
    }
    
    public void setA4ColorPerfil(Double a4ColorPerfil) {
        this.a4ColorPerfil = a4ColorPerfil;
    }
    public Double getA4PbPerfil() {
        return this.a4PbPerfil;
    }
    
    public void setA4PbPerfil(Double a4PbPerfil) {
        this.a4PbPerfil = a4PbPerfil;
    }
    public Double getA3ColorPerfil() {
        return this.a3ColorPerfil;
    }
    
    public void setA3ColorPerfil(Double a3ColorPerfil) {
        this.a3ColorPerfil = a3ColorPerfil;
    }
    public Double getA3PbPerfil() {
        return this.a3PbPerfil;
    }
    
    public void setA3PbPerfil(Double a3PbPerfil) {
        this.a3PbPerfil = a3PbPerfil;
    }
    public Double getOutrosPbPerfil() {
        return this.outrosPbPerfil;
    }
    
    public void setOutrosPbPerfil(Double outrosPbPerfil) {
        this.outrosPbPerfil = outrosPbPerfil;
    }
    public Double getOutrosColorPerfil() {
        return this.outrosColorPerfil;
    }
    
    public void setOutrosColorPerfil(Double outrosColorPerfil) {
        this.outrosColorPerfil = outrosColorPerfil;
    }
    public Set getTems() {
        return this.tems;
    }
    
    public void setTems(Set tems) {
        this.tems = tems;
    }




}


