package stoni_bean;
// Generated 24/08/2017 11:33:26 by Hibernate Tools 4.3.1



/**
 * Tem generated by hbm2java
 */
public class Tem  implements java.io.Serializable {


     private TemId id;
     private Equipamento equipamento;
     private Identidade identidade;
     private Impressora impressora;
     private Preco preco;

    public Tem() {
    }

    public Tem(TemId id, Equipamento equipamento, Identidade identidade, Impressora impressora, Preco preco) {
       this.id = id;
       this.equipamento = equipamento;
       this.identidade = identidade;
       this.impressora = impressora;
       this.preco = preco;
    }
   
    public TemId getId() {
        return this.id;
    }
    
    public void setId(TemId id) {
        this.id = id;
    }
    public Equipamento getEquipamento() {
        return this.equipamento;
    }
    
    public void setEquipamento(Equipamento equipamento) {
        this.equipamento = equipamento;
    }
    public Identidade getIdentidade() {
        return this.identidade;
    }
    
    public void setIdentidade(Identidade identidade) {
        this.identidade = identidade;
    }
    public Impressora getImpressora() {
        return this.impressora;
    }
    
    public void setImpressora(Impressora impressora) {
        this.impressora = impressora;
    }
    public Preco getPreco() {
        return this.preco;
    }
    
    public void setPreco(Preco preco) {
        this.preco = preco;
    }




}


