package stoni_bean;
// Generated 24/08/2017 11:33:26 by Hibernate Tools 4.3.1



/**
 * TemId generated by hbm2java
 */
public class TemId  implements java.io.Serializable {


     private int idEquipamento;
     private int idImpressora;
     private int idPerfil;
     private int idIdentidade;

    public TemId() {
    }

    public TemId(int idEquipamento, int idImpressora, int idPerfil, int idIdentidade) {
       this.idEquipamento = idEquipamento;
       this.idImpressora = idImpressora;
       this.idPerfil = idPerfil;
       this.idIdentidade = idIdentidade;
    }
   
    public int getIdEquipamento() {
        return this.idEquipamento;
    }
    
    public void setIdEquipamento(int idEquipamento) {
        this.idEquipamento = idEquipamento;
    }
    public int getIdImpressora() {
        return this.idImpressora;
    }
    
    public void setIdImpressora(int idImpressora) {
        this.idImpressora = idImpressora;
    }
    public int getIdPerfil() {
        return this.idPerfil;
    }
    
    public void setIdPerfil(int idPerfil) {
        this.idPerfil = idPerfil;
    }
    public int getIdIdentidade() {
        return this.idIdentidade;
    }
    
    public void setIdIdentidade(int idIdentidade) {
        this.idIdentidade = idIdentidade;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TemId) ) return false;
		 TemId castOther = ( TemId ) other; 
         
		 return (this.getIdEquipamento()==castOther.getIdEquipamento())
 && (this.getIdImpressora()==castOther.getIdImpressora())
 && (this.getIdPerfil()==castOther.getIdPerfil())
 && (this.getIdIdentidade()==castOther.getIdIdentidade());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdEquipamento();
         result = 37 * result + this.getIdImpressora();
         result = 37 * result + this.getIdPerfil();
         result = 37 * result + this.getIdIdentidade();
         return result;
   }   


}


